/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_uas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Agung Yuda
 */
public class fReport extends javax.swing.JFrame {

    /**
     * Creates new form fReport
     */
    private DefaultTableModel model;

    public fReport() {
        initComponents();
        model = new DefaultTableModel();
        tabelinput.setModel(model);
        model.addColumn("No Faktur");
        model.addColumn("Nama Makanan");
        model.addColumn("Harga Satuan");
        model.addColumn("Jumlah Jual");
        model.addColumn("Total Harga");
        model.addColumn("Tanggal Penjualan");
    }

    private String getUniqueFilePath(String directoryPath, String baseFileName) {
        File file = new File(directoryPath, baseFileName);
        if (!file.exists()) {
            return file.getAbsolutePath();
        }

        String nameWithoutExtension = baseFileName.substring(0, baseFileName.lastIndexOf('.'));
        String extension = baseFileName.substring(baseFileName.lastIndexOf('.'));
        int count = 1;

        while (file.exists()) {
            String newFileName = nameWithoutExtension + "(" + count + ")" + extension;
            file = new File(directoryPath, newFileName);
            count++;
        }

        return file.getAbsolutePath();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LaporanPenjualan = new javax.swing.JLabel();
        btn_back1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        startDate = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        btn_generatePDF = new javax.swing.JButton();
        label_totalPendapatan = new javax.swing.JLabel();
        txt_totalPendapatan2 = new javax.swing.JLabel();
        endDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelinput = new javax.swing.JTable();
        spinnerStartDate = new javax.swing.JSpinner();
        spinnerEndDate = new javax.swing.JSpinner();
        btn_clear = new javax.swing.JButton();
        checkbox_DineIn = new javax.swing.JCheckBox();
        checkbox_TakeAway = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        LaporanPenjualan.setFont(new java.awt.Font("Cambria", 1, 28)); // NOI18N
        LaporanPenjualan.setText("Restaurant Income Report");

        btn_back1.setBackground(new java.awt.Color(255, 255, 255));
        btn_back1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back1.setText("Back");
        btn_back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LaporanPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back1)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back1)
                    .addComponent(LaporanPenjualan))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));

        startDate.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        startDate.setForeground(new java.awt.Color(255, 255, 255));
        startDate.setText("Start Date");

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_generatePDF.setText("Generate PDF");
        btn_generatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generatePDFActionPerformed(evt);
            }
        });

        label_totalPendapatan.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        label_totalPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        label_totalPendapatan.setText("Total Pendapatan: Rp.");

        txt_totalPendapatan2.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txt_totalPendapatan2.setForeground(new java.awt.Color(255, 255, 255));

        endDate.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        endDate.setForeground(new java.awt.Color(255, 255, 255));
        endDate.setText("End Date");

        tabelinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelinputMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelinput);

        spinnerStartDate.setModel(new javax.swing.SpinnerDateModel());

        spinnerEndDate.setModel(new javax.swing.SpinnerDateModel());

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        checkbox_DineIn.setText(" Dine In");

        checkbox_TakeAway.setText("Take Away");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_totalPendapatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_totalPendapatan2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDate)
                            .addComponent(checkbox_DineIn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkbox_TakeAway)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spinnerEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btn_cari)
                                .addGap(18, 18, 18)
                                .addComponent(btn_generatePDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(endDate)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDate)
                    .addComponent(endDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari)
                    .addComponent(btn_generatePDF)
                    .addComponent(btn_clear))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_DineIn)
                    .addComponent(checkbox_TakeAway))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_totalPendapatan)
                    .addComponent(txt_totalPendapatan2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);

        java.util.Date startDate = (java.util.Date) spinnerStartDate.getValue();
        java.util.Date endDate = (java.util.Date) spinnerEndDate.getValue();
        java.sql.Date sqlStartDate = new java.sql.Date(startDate.getTime());
        java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());

        try {
            Connection c = koneksi.getKoneksi();
            String sql = "";

            if (checkbox_DineIn.isSelected() && !checkbox_TakeAway.isSelected()) {
                sql = "SELECT * FROM tb_penjualan WHERE tanggal_penjualan BETWEEN ? AND ?";
            } else if (!checkbox_DineIn.isSelected() && checkbox_TakeAway.isSelected()) {
                sql = "SELECT * FROM tb_penjualan2 WHERE tanggal_penjualan BETWEEN ? AND ?";
            } else {
                JOptionPane.showMessageDialog(this, "Please select only one option: Dine In or Take Away.");
                return;
            }

            PreparedStatement p = c.prepareStatement(sql);
            p.setDate(1, sqlStartDate);
            p.setDate(2, sqlEndDate);

            ResultSet r = p.executeQuery();
            while (r.next()) {
                Object[] rowData = {
                    r.getString("no_faktur"),
                    r.getString("nama_makanan"),
                    r.getInt("harga_satuan"),
                    r.getInt("jumlah_makanan"),
                    r.getInt("total_harga"),
                    r.getDate("tanggal_penjualan")
                };
                model.addRow(rowData);
            }
            r.close();
            p.close();

            String sqlTotal = sql.replace("*", "SUM(total_harga) AS totalPendapatan");
            p = c.prepareStatement(sqlTotal);
            p.setDate(1, sqlStartDate);
            p.setDate(2, sqlEndDate);
            r = p.executeQuery();
            if (r.next()) {
                txt_totalPendapatan2.setText(String.valueOf(r.getInt("totalPendapatan")));
            }
            r.close();
            p.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error occurred: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_generatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generatePDFActionPerformed
        // TODO add your handling code here:
        Document document = new Document();
        try {
            String directoryPath = "C:/Users/adiyo/OneDrive/Documents";
            String filePath = directoryPath + "/LaporanPenjualan_RestaurantKita.pdf";

            filePath = getUniqueFilePath(directoryPath, "LaporanPenjualan_RestaurantKita.pdf");

            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();

            Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 20, Font.BOLD);
            Font boldFont2 = new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.BOLD);
            Paragraph title = new Paragraph("Laporan Penjualan Restaurant Kita", boldFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph(" "));

            Date startDate = (Date) spinnerStartDate.getValue();
            Date endDate = (Date) spinnerEndDate.getValue();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

            String formattedStartDate = dateFormat.format(startDate);
            String formattedEndDate = dateFormat.format(endDate);

            Paragraph dateRange = new Paragraph("Periode: " + formattedStartDate + " s/d " + formattedEndDate);
            dateRange.setAlignment(Element.ALIGN_CENTER);
            document.add(dateRange);
            document.add(new Paragraph(" "));

            PdfPTable tablePenjualan = new PdfPTable(6);
            tablePenjualan.setWidthPercentage(100);
            tablePenjualan.setSpacingBefore(10f);
            tablePenjualan.setSpacingAfter(10f);

            String[] headers = {"No Faktur", "Nama Makanan", "Harga Satuan", "Jumlah Jual", "Total Harga", "Tanggal Penjualan"};
            for (String header : headers) {
                PdfPCell headerCell = new PdfPCell(new Phrase(header, boldFont2));
                headerCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tablePenjualan.addCell(headerCell);
            }

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    tablePenjualan.addCell(model.getValueAt(i, j).toString());
                }
            }

            document.add(tablePenjualan);
            String totalPendapatan = txt_totalPendapatan2.getText();
            Paragraph totalPendapatanParagraph = new Paragraph("Total Pendapatan: " + totalPendapatan, boldFont2);
            totalPendapatanParagraph.setAlignment(Element.ALIGN_RIGHT);
            document.add(totalPendapatanParagraph);
            document.close();

            JOptionPane.showMessageDialog(this, "PDF Generated Successfully at " + filePath);

            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(new File(filePath));
            }

        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_generatePDFActionPerformed

    private void tabelinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelinputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelinputMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        txt_totalPendapatan2.setText("");
        checkbox_DineIn.setSelected(false);
        checkbox_TakeAway.setSelected(false);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        fmenu fm = new fmenu();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LaporanPenjualan;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_generatePDF;
    private javax.swing.JCheckBox checkbox_DineIn;
    private javax.swing.JCheckBox checkbox_TakeAway;
    private javax.swing.JLabel endDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_totalPendapatan;
    private javax.swing.JSpinner spinnerEndDate;
    private javax.swing.JSpinner spinnerStartDate;
    private javax.swing.JLabel startDate;
    private javax.swing.JTable tabelinput;
    private javax.swing.JLabel txt_totalPendapatan2;
    // End of variables declaration//GEN-END:variables
}
